PRACT3A SEGMENT BYTE PUBLIC 'CODE'
ASSUME CS: PRACT3A
	PUBLIC _comprobarNumeroSecreto, _rellenarIntento
	_comprobarNumeroSecreto PROC FAR
		PUSH BP
		MOV BP, SP ;COLOCAMOS EL PUNTERO EN LA CIMA DE LA PILA
		
		LES DI, [BP+6] ;SEGMENT=>ES OFFSET=>DI
		
		;METEMOS LOS 4 NUMEROS EN REGISTROS
		MOV AH, ES[DI] 
		MOV AL, ES[DI+1]
		MOV BH, ES[DI+2]
		MOV BL, ES[DI+3]
		
		;COMPRUEBA SI HAY NUMEROS REPETIDOS, SI LOS HAY SALTA A FALLO
		CMP AH, AL
		JE FALLO
		CMP AH, BH
		JE FALLO
		CMP AH, BL
		JE FALLO
		CMP AL, BH
		JE FALLO
		CMP AL, BL
		JE FALLO
		CMP BH, BL
		JE FALLO
		
		MOV AX, 0
		POP BP
		RET ;DEVUELVE CERO SI NO HAY REPETIDOS
		
	FALLO:
		MOV AX, 1
		POP BP
		RET ;DEVUELVE UNO SI HAY REPETIDOS
	_comprobarNumeroSecreto ENDP

	_rellenarIntento PROC FAR
		PUSH BP
		MOV BP, SP ;COLOCAMOS EL PUNTERO EN LA CIMA DE LA PILA
		
		LES DI, [BP+10] ;SEGMENT=>ES OFFSET=>DI
		
		MOV AX, [BP+6]
	
	_rellenarIntento ENDP
	
PRACT3A ENDS
END