PRACT3B SEGMENT BYTE PUBLIC 'CODE'
ASSUME CS: PRACT3B
	PUBLIC _calcularAciertos, _calcularSemiaciertos
	_calcularAciertos PROC FAR
		PUSH BP
		MOV BP, SP ;COLOCAMOS EL PUNTERO EN LA CIMA DE LA PILA
		
		PUSH DI BX CX ;GUARDAMOS REGISTROS USADOS

		LES DI, [BP+12] ;SEGMENT=>ES OFFSET=>DI
		
		;METEMOS LOS 4 NUMEROS DEL INTENTO EN REGISTROS
		MOV BH, ES[DI] 
		MOV BL, ES[DI+1]
		MOV CH, ES[DI+2]
		MOV CL, ES[DI+3]

		;CAMBIAMOS AL CODIGO CORRECTO
		LES DI, [BP+16] ;SEGMENT=>ES OFFSET=>DI
		
		;COMPRUEBA SI COINCIDEN NUMEROS, Y SI COINCIDEN INCREMENTA UN CONTADOR
		MOV AX, 0

		CMP BH, ES[DI]
		JNE SEGUNDO
		INC AX
	SEGUNDO:
		CMP BL, ES[DI+1]
		JNE TERCERO
		INC AX
	TERCERO:
		CMP CH, ES[DI+2]
		JNE CUARTO
		INC AX
	CUARTO:
		CMP CL, ES[DI+3]
		JNE FIN
		INC AX
	FIN:
		
		POP CX BX DI BP
		RET ;DEVUELVE EL CONTENIDO DEL CONTADOR (AX)
	_calcularAciertos ENDP
	
	_calcularSemiaciertos PROC FAR
	PUSH BP
	MOV BP, SP ;COLOCAMOS EL PUNTERO EN LA CIMA DE LA PILA
	
	LES DI, [BP+10] ;SEGMENT=>ES OFFSET=>DI
	
	MOV AX, [BP+6]
	
	_calcularSemiaciertos ENDP
	
PRACT3B ENDS
END