all: pract2b.exe

pract2a.exe: pract2a.obj
    tlink /v pract2a.obj

pract2a.obj: pract2a.asm
    tasm /zi pract2a.asm


pract2b.exe: pract2b.obj
    tlink /v pract2b.obj

pract2b.obj: pract2b.asm
    tasm /zi pract2b.asm


pract2c.exe: pract2c.obj
    tlink /v pract2c.obj

pract2c.obj: pract2c.asm
    tasm /zi pract2c.asm